version: "3.7"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api_db
    volumes:
      - .:/data/postgres
  app:
    build: .
    container_name: fin_api
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local
